import "./globals.css";
import { Sora } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "ClearTripp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex flex-col flex-grow">
            <Navbar />
            <main className="flex-grow p-2 bg-backgroundGray">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
